server:
  port: 6969
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myflea?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: root
    password: d1227731421R
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 20MB
  thymeleaf:
    enabled: true  #开启thymeleaf视图解析
    encoding: utf-8  #编码
    prefix: classpath:/templates/  #前缀
    cache: false  #是否使用缓存
    mode: HTML  #严格的HTML语法模式
    suffix: .html  #后缀名
  mvc:
    static-path-pattern: /static/**
logging:
  level:
    com.demo: debug
fdfs:
  so-timeout: 250
  connect-timeout: 600
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 172.18.0.3:22122
